### ISSUE TITLE
Tests timeout

### ISSUE THREAD

**Issue by homerlex** [AgoraIO-Community/Agora-RTM-Nodejs#2]
When I run the tests I get the errors below.  I did set the `AGORA_APP_ID` in the .env file

```
npm run test

> agora-node-rtm@1.0.0 test /home/vagrant/vagrant-workspace/Agora-RTM-Nodejs
> jest --setupFiles dotenv/config --forceExit

 FAIL  __tests__/adpter.test.ts (31.387s)
  â— Console

  
  â— Adapter API Test â€º Join/Leave

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      2 | 
      3 | describe('Adapter API Test', () => {
    > 4 |   it('Join/Leave', async () => {
        |   ^
      5 |     const engine = new AgoraRTM();
      6 |     console.log("!!!", process.env.AGORA_APP_ID);
      7 |     await engine.login(process.env.AGORA_APP_ID, 'ttyy')

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:101:22)
      at Suite.it (__tests__/adpter.test.ts:4:3)
      at Object.describe (__tests__/adpter.test.ts:3:1)

  â— Adapter API Test â€º MemberJoined

    Timeout - Async callback was not invoked within the 15000ms timeout specified by jest.setTimeout.

      12 |   })
      13 | 
    > 14 |   it('MemberJoined', async () => {
         |   ^
      15 |     const cb = jest.fn()
      16 |     const engine1 = new AgoraRTM();
      17 |     await engine1.login(process.env.AGORA_APP_ID, 'ttyy1')

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:101:22)
      at Suite.it (__tests__/adpter.test.ts:14:3)
      at Object.describe (__tests__/adpter.test.ts:3:1)


 RUNS  __tests__/rtm.test.ts
Segmentation fault (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 139
npm ERR! agora-node-rtm@1.0.0 test: `jest --setupFiles dotenv/config --forceExit`
npm ERR! Exit status 139
npm ERR! 
npm ERR! Failed at the agora-node-rtm@1.0.0 test script.
```

**Comment by plutoless** [comment]
you will need to set AGORA_APP_ID in your environment variables to successfully login

**Comment by homerlex** [comment]
@plutoless - As I mentioned above I did set the AGORA_APP_ID in .env.  I put console.log in the test to make sure it was being set.  I still get the timeouts.

**Comment by homerlex** [comment]
Are there any special ports that need to be opened on my server?

**Comment by plutoless** [comment]
ahh sorry. we've updated the login api once, the test was not adapted to the change. i'll fix the test now

**Comment by homerlex** [comment]
OK - thanks for the quick replies!

**Comment by plutoless** [comment]
devops@devops-VirtualBox:~/Desktop/Agora-RTM-Nodejs$ npm run test

> agora-node-rtm@1.0.0 test /home/devops/Desktop/Agora-RTM-Nodejs
> jest --setupFiles dotenv/config --forceExit

 PASS  __tests__/adpter.test.ts
 PASS  __tests__/rtm.test.ts

Test Suites: 2 passed, 2 total
Tests:       6 passed, 6 total
Snapshots:   0 total
Time:        4.023s

fixed

**Comment by homerlex** [comment]
@plutoless - The tests still fail for me.  How does can it work with a null token?

I modified one of the tests to include a token that I generated for the ttyy channel and it works:

```
  it('Join/Leave', async () => {
    const engine = new AgoraRTM();
    const token = "006aafc1ec595164ffd8d78c0d6d2cee2abIAA969Tz5SuzE8X5CCY3uUQ4ZELBH1P1n6OgER87bYDznnwjxUEAAAAAEAA0shE1vd8pXQEAAQC/3yld";
    console.log("!!!", process.env.AGORA_APP_ID);
    engine.initialize(process.env.AGORA_APP_ID);
    await engine.login(token, 'ttyy')
    const channel = engine.createChannel('ttyy');
    await channel.join();
    await channel.leave();
    expect(true)
  })
```

The adpter tests don't timeout anymore but they fail:
```
FAIL  __tests__/adpter.test.ts
  â— Adapter API Test â€º Join/Leave

    Failed: 2

      2 | 
      3 | describe('Adapter API Test', () => {
    > 4 |   it('Join/Leave', async () => {
        |   ^
      5 |     const engine = new AgoraRTM();
      6 |     engine.initialize(process.env.AGORA_APP_ID)
      7 |     await engine.login(null, 'ttyy')

      at Env.it (node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:91:24)
      at Suite.it (__tests__/adpter.test.ts:4:3)
      at Object.describe (__tests__/adpter.test.ts:3:1)

  â— Adapter API Test â€º MemberJoined

    Failed: 2

      12 |   })
      13 | 
    > 14 |   it('MemberJoined', async () => {
         |   ^
      15 |     const cb = jest.fn()
      16 |     const engine1 = new AgoraRTM();
      17 |     engine1.initialize(process.env.AGORA_APP_ID)

      at Env.it (node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:91:24)
      at Suite.it (__tests__/adpter.test.ts:14:3)
      at Object.describe (__tests__/adpter.test.ts:3:1)
```

The rtm tests still timeout
```
FAIL  __tests__/rtm.test.ts (15.748s)
  â— C++ Addon API Test â€º Login

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

       5 | 
       6 | describe('C++ Addon API Test', () => {
    >  7 |   it('Login', (done) => {
         |   ^
       8 |     client = createInstance();
       9 |     client.initialize(process.env.AGORA_APP_ID)
      10 |     client.onEvent('LoginSuccess', () => {

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:101:22)
      at Suite.it (__tests__/rtm.test.ts:7:3)
      at Object.describe (__tests__/rtm.test.ts:6:1)

  â— C++ Addon API Test â€º Join Channel

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      14 |     client.login(null, 'ttyy')
      15 |   })
    > 16 |   it('Join Channel', (done) => {
         |   ^
      17 |     channel = client.createChannel('agoratest')
      18 |       
      19 |     channel.onEvent('JoinSuccess', () => {

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:101:22)
      at Suite.it (__tests__/rtm.test.ts:16:3)
      at Object.describe (__tests__/rtm.test.ts:6:1)

  â— C++ Addon API Test â€º Complex Join/Leave

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      30 |     channel.getMembers()
      31 |   })
    > 32 |   it('Complex Join/Leave', (done) => {
         |   ^
      33 |     channel.leave();
      34 |     channel.onEvent('LeaveChannel', (e) => {
      35 |       channel = client.createChannel('agoraAnotherTest');

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:101:22)
      at Suite.it (__tests__/rtm.test.ts:32:3)
      at Object.describe (__tests__/rtm.test.ts:6:1)
```

**Comment by plutoless** [comment]
@homerlex  my appid has not turned on token so i don't need to pass any token while calling login. If you turned on token in your dashboard then you need to specify it in the test yes.

**Comment by homerlex** [comment]
Got it. Thanks! - I have them passing with a different app id (no token needed)

**Comment by mohammedrafathz** [comment]
Hey @plutoless, I am having the same issue as mentioned by @homerlex.  I tried multiple API keys with and without token generated but it doesn't help. The tests fail anyhow. Please refer the code below. 

`  FAIL  __tests__/adpter.test.ts (14.002s)
  ● Console

    console.log __tests__/adpter.test.ts:7
      !!! 

  ● Adapter API Test › Join/Leave

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      2 | 
      3 | describe('Adapter API Test', () => {
    > 4 |   it('Join/Leave', async () => {
        |   ^
      5 |     const engine = new AgoraRTM();
      6 |     const token = null
      7 |     console.log("!!!", process.env.AGORA_APP_ID);

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:101:22)
      at Suite.it (__tests__/adpter.test.ts:4:3)
      at Object.describe (__tests__/adpter.test.ts:3:1)

  ● Adapter API Test › Invalid channel

    expect(received).toBe(expected) // Object.is equality

    Expected: null
    Received: {"_events": {}, "_eventsCount": 0, "_maxListeners": undefined, "channel": {}, "mutex": {"lockers": Map {}}, "subscribeEvents": [Function anonymous]}

    Difference:

      Comparing two different types of values. Expected null but received object.

      20 |     await engine1.login(null, 'ttyy1')
      21 |     const channel1 = engine1.createChannel('非法频道');
    > 22 |     expect(channel1).toBe(null);
         |                      ^
      23 |   })
      24 | 
      25 |   it('MemberJoined', async () => {

      at toBe (__tests__/adpter.test.ts:22:22)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

  ● Adapter API Test › MemberJoined

    Failed: 4

      2 | 
      3 | describe('Adapter API Test', () => {
    > 4 |   it('Join/Leave', async () => {
        |   ^
      5 |     const engine = new AgoraRTM();
      6 |     const token = null
      7 |     console.log("!!!", process.env.AGORA_APP_ID);

      at Env.it (node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:91:24)
      at Suite.it (__tests__/adpter.test.ts:4:3)
      at Object.describe (__tests__/adpter.test.ts:3:1)

  ● Adapter API Test › MemberJoined

    Failed: 4

      23 |   })
      24 | 
    > 25 |   it('MemberJoined', async () => {
         |   ^
      26 |     const cb = jest.fn()
      27 |     const engine1 = new AgoraRTM();
      28 |     engine1.initialize(process.env.AGORA_APP_ID)

      at Env.it (node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:91:24)
      at Suite.it (__tests__/adpter.test.ts:25:3)
      at Object.describe (__tests__/adpter.test.ts:3:1)

 FAIL  __tests__/rtm.test.ts (19.215s)
  ● C++ Addon API Test › Login

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

       5 | 
       6 | describe('C++ Addon API Test', () => {
    >  7 |   it('Login', (done) => {
         |   ^
       8 |     client = createInstance();
       9 |     client.initialize(process.env.AGORA_APP_ID)
      10 |     client.onEvent('LoginSuccess', () => {

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:101:22)
      at Suite.it (__tests__/rtm.test.ts:7:3)
      at Object.describe (__tests__/rtm.test.ts:6:1)

  ● C++ Addon API Test › GetMembers

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      24 |     channel.join()
      25 |   })
    > 26 |   it('GetMembers', (done) => {
         |   ^
      27 |     channel.onEvent('GetMembers', members => {
      28 |       expect(true);
      29 |       done();

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:101:22)
      at Suite.it (__tests__/rtm.test.ts:26:3)
      at Object.describe (__tests__/rtm.test.ts:6:1)

  ● C++ Addon API Test › Complex Join/Leave

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      31 |     channel.getMembers()
      32 |   })
    > 33 |   it('Complex Join/Leave', (done) => {
         |   ^
      34 |     channel.leave();
      35 |     channel.onEvent('LeaveChannel', (e) => {
      36 |       channel = client.createChannel('agoraAnotherTest');

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:101:22)
      at Suite.it (__tests__/rtm.test.ts:33:3)
      at Object.describe (__tests__/rtm.test.ts:6:1)

Test Suites: 2 failed, 2 total
Tests:       6 failed, 1 passed, 7 total
Snapshots:   0 total
Time:        20.872s, estimated 22s
Ran all test suites.
Force exiting Jest`
