### ISSUE TITLE
Test Suites failed

### ISSUE THREAD

**Issue by mohammedrafathz** [AgoraIO-Community/Agora-RTM-Nodejs#5]
Hey @plutoless, I am having the same issue as mentioned by @homerlex.  I tried multiple API keys with and without token generated but it doesn't help. The tests fail anyhow. Please refer the code below. 

`  FAIL  __tests__/adpter.test.ts (14.002s)
  ● Console

    console.log __tests__/adpter.test.ts:7
      !!! 

  ● Adapter API Test › Join/Leave

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      2 | 
      3 | describe('Adapter API Test', () => {
    > 4 |   it('Join/Leave', async () => {
        |   ^
      5 |     const engine = new AgoraRTM();
      6 |     const token = null
      7 |     console.log("!!!", process.env.AGORA_APP_ID);

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:101:22)
      at Suite.it (__tests__/adpter.test.ts:4:3)
      at Object.describe (__tests__/adpter.test.ts:3:1)

  ● Adapter API Test › Invalid channel

    expect(received).toBe(expected) // Object.is equality

    Expected: null
    Received: {"_events": {}, "_eventsCount": 0, "_maxListeners": undefined, "channel": {}, "mutex": {"lockers": Map {}}, "subscribeEvents": [Function anonymous]}

    Difference:

      Comparing two different types of values. Expected null but received object.

      20 |     await engine1.login(null, 'ttyy1')
      21 |     const channel1 = engine1.createChannel('非法频道');
    > 22 |     expect(channel1).toBe(null);
         |                      ^
      23 |   })
      24 | 
      25 |   it('MemberJoined', async () => {

      at toBe (__tests__/adpter.test.ts:22:22)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

  ● Adapter API Test › MemberJoined

    Failed: 4

      2 | 
      3 | describe('Adapter API Test', () => {
    > 4 |   it('Join/Leave', async () => {
        |   ^
      5 |     const engine = new AgoraRTM();
      6 |     const token = null
      7 |     console.log("!!!", process.env.AGORA_APP_ID);

      at Env.it (node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:91:24)
      at Suite.it (__tests__/adpter.test.ts:4:3)
      at Object.describe (__tests__/adpter.test.ts:3:1)

  ● Adapter API Test › MemberJoined

    Failed: 4

      23 |   })
      24 | 
    > 25 |   it('MemberJoined', async () => {
         |   ^
      26 |     const cb = jest.fn()
      27 |     const engine1 = new AgoraRTM();
      28 |     engine1.initialize(process.env.AGORA_APP_ID)

      at Env.it (node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:91:24)
      at Suite.it (__tests__/adpter.test.ts:25:3)
      at Object.describe (__tests__/adpter.test.ts:3:1)

 FAIL  __tests__/rtm.test.ts (19.215s)
  ● C++ Addon API Test › Login

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

       5 | 
       6 | describe('C++ Addon API Test', () => {
    >  7 |   it('Login', (done) => {
         |   ^
       8 |     client = createInstance();
       9 |     client.initialize(process.env.AGORA_APP_ID)
      10 |     client.onEvent('LoginSuccess', () => {

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:101:22)
      at Suite.it (__tests__/rtm.test.ts:7:3)
      at Object.describe (__tests__/rtm.test.ts:6:1)

  ● C++ Addon API Test › GetMembers

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      24 |     channel.join()
      25 |   })
    > 26 |   it('GetMembers', (done) => {
         |   ^
      27 |     channel.onEvent('GetMembers', members => {
      28 |       expect(true);
      29 |       done();

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:101:22)
      at Suite.it (__tests__/rtm.test.ts:26:3)
      at Object.describe (__tests__/rtm.test.ts:6:1)

  ● C++ Addon API Test › Complex Join/Leave

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      31 |     channel.getMembers()
      32 |   })
    > 33 |   it('Complex Join/Leave', (done) => {
         |   ^
      34 |     channel.leave();
      35 |     channel.onEvent('LeaveChannel', (e) => {
      36 |       channel = client.createChannel('agoraAnotherTest');

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:101:22)
      at Suite.it (__tests__/rtm.test.ts:33:3)
      at Object.describe (__tests__/rtm.test.ts:6:1)

Test Suites: 2 failed, 2 total
Tests:       6 failed, 1 passed, 7 total
Snapshots:   0 total
Time:        20.872s, estimated 22s
Ran all test suites.
Force exiting Jest`

_Originally posted by @mohammedrafathz in https://github.com/AgoraIO-Community/Agora-RTM-Nodejs/issues/2#issuecomment-543839824_

**Comment by plutoless** [comment]
fixed

**Comment by mohammedrafathz** [comment]
Build still fails with following logs, when I run `npm install`:
> agora-node-rtm@1.0.0 install /home/risky-boy/Documents/Projects/Agora/Agora-RTM-Nodejs
> node-gyp rebuild

make: Entering directory '/home/risky-boy/Documents/Projects/Agora/Agora-RTM-Nodejs/build'
  CXX(target) Release/obj.target/agorasdk/addon/node_uid.o
  CXX(target) Release/obj.target/agorasdk/addon/node_napi_api.o
  CXX(target) Release/obj.target/agorasdk/addon/node_async_queue.o
  CXX(target) Release/obj.target/agorasdk/addon/rtm_controller.o
In file included from ../addon/rtm_controller.h:22:0,
                 from ../addon/rtm_controller.cc:4:
../addon/IAgoraRtmService.h: In member function ‘virtual void agora::rtm::IChannelEventHandler::onJoinFailure(agora::rtm::JOIN_CHANNEL_ERR)’:
../addon/IAgoraRtmService.h:350:11: warning: statement has no effect [-Wunused-value]
           (JOIN_CHANNEL_ERR) errorCode;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h: In member function ‘virtual void agora::rtm::IChannelEventHandler::onLeave(agora::rtm::LEAVE_CHANNEL_ERR)’:
../addon/IAgoraRtmService.h:357:11: warning: statement has no effect [-Wunused-value]
           (LEAVE_CHANNEL_ERR) errorCode;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h: In member function ‘virtual void agora::rtm::IChannelEventHandler::onMessageReceived(const char*, const agora::rtm::IMessage*)’:
../addon/IAgoraRtmService.h:367:11: warning: statement has no effect [-Wunused-value]
           (const char *) userId;
           ^~~~~~~~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h:368:11: warning: statement has no effect [-Wunused-value]
           (IMessage *) message;
           ^~~~~~~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h: In member function ‘virtual void agora::rtm::IChannelEventHandler::onSendMessageResult(long long int, agora::rtm::CHANNEL_MESSAGE_ERR_CODE)’:
../addon/IAgoraRtmService.h:378:11: warning: statement has no effect [-Wunused-value]
           (long long) messageId;
           ^~~~~~~~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h:379:11: warning: statement has no effect [-Wunused-value]
           (CHANNEL_MESSAGE_ERR_CODE) state;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h: In member function ‘virtual void agora::rtm::IChannelEventHandler::onMemberJoined(agora::rtm::IChannelMember*)’:
../addon/IAgoraRtmService.h:387:11: warning: statement has no effect [-Wunused-value]
           (IChannelMember *) member;
           ^~~~~~~~~~~~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h: In member function ‘virtual void agora::rtm::IChannelEventHandler::onMemberLeft(agora::rtm::IChannelMember*)’:
../addon/IAgoraRtmService.h:395:11: warning: statement has no effect [-Wunused-value]
           (IChannelMember *) member;
           ^~~~~~~~~~~~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h: In member function ‘virtual void agora::rtm::IChannelEventHandler::onGetMembers(agora::rtm::IChannelMember**, int, agora::rtm::GET_MEMBERS_ERR)’:
../addon/IAgoraRtmService.h:405:11: warning: statement has no effect [-Wunused-value]
           (IChannelMember **) members;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h:406:11: warning: statement has no effect [-Wunused-value]
           (int) userCount;
           ^~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h: In member function ‘virtual void agora::rtm::IRtmServiceEventHandler::onLoginFailure(agora::rtm::LOGIN_ERR_CODE)’:
../addon/IAgoraRtmService.h:494:11: warning: statement has no effect [-Wunused-value]
           (LOGIN_ERR_CODE) errorCode;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h: In member function ‘virtual void agora::rtm::IRtmServiceEventHandler::onRenewTokenResult(const char*, agora::rtm::RENEW_TOKEN_ERR_CODE)’:
../addon/IAgoraRtmService.h:499:11: warning: statement has no effect [-Wunused-value]
           (const char*) token;
           ^~~~~~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h:500:11: warning: statement has no effect [-Wunused-value]
           (RENEW_TOKEN_ERR_CODE) errorCode;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h: In member function ‘virtual void agora::rtm::IRtmServiceEventHandler::onLogout(agora::rtm::LOGOUT_ERR_CODE)’:
../addon/IAgoraRtmService.h:512:11: warning: statement has no effect [-Wunused-value]
           (LOGOUT_ERR_CODE) errorCode;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h: In member function ‘virtual void agora::rtm::IRtmServiceEventHandler::onSendMessageResult(long long int, agora::rtm::PEER_MESSAGE_ERR_CODE)’:
../addon/IAgoraRtmService.h:528:11: warning: statement has no effect [-Wunused-value]
           (long long) messageId;
           ^~~~~~~~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h:529:11: warning: statement has no effect [-Wunused-value]
           (PEER_MESSAGE_ERR_CODE) errorCode;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h: In member function ‘virtual void agora::rtm::IRtmServiceEventHandler::onMessageReceivedFromPeer(const char*, const agora::rtm::IMessage*)’:
../addon/IAgoraRtmService.h:538:11: warning: statement has no effect [-Wunused-value]
           (char *) peerId;
           ^~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h:539:11: warning: statement has no effect [-Wunused-value]
           (IMessage *) message;
           ^~~~~~~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h: In member function ‘virtual void agora::rtm::IRtmServiceEventHandler::onQueryPeersOnlineStatusResult(long long int, const agora::rtm::PeerOnlineStatus*, int, agora::rtm::QUERY_PEERS_ONLINE_STATUS_ERR)’:
../addon/IAgoraRtmService.h:544:11: warning: statement has no effect [-Wunused-value]
           (long long) requestId;
           ^~~~~~~~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h:545:11: warning: statement has no effect [-Wunused-value]
           (const PeerOnlineStatus*) peersStatus;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h:546:11: warning: statement has no effect [-Wunused-value]
           (int) peerCount;
           ^~~~~~~~~~~~~~~
../addon/IAgoraRtmService.h:547:11: warning: statement has no effect [-Wunused-value]
           (QUERY_PEERS_ONLINE_STATUS_ERR) errorCode;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../addon/rtm_controller.cc:4:0:
../addon/rtm_controller.h: At global scope:
../addon/rtm_controller.h:84:17: error: ‘PEER_ONLINE_STATE’ in namespace ‘agora::rtm’ does not name a type
     agora::rtm::PEER_ONLINE_STATE onlineState;
                 ^~~~~~~~~~~~~~~~~
../addon/rtm_controller.cc: In static member function ‘static void agora::lb_linux_sdk::RtmServerController::initialize(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../addon/rtm_controller.cc:188:12: warning: unused variable ‘cid’ [-Wunused-variable]
   uint32_t cid;
            ^~~
../addon/rtm_controller.cc: In static member function ‘static void agora::lb_linux_sdk::RtmServerController::login(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../addon/rtm_controller.cc:202:12: warning: unused variable ‘cid’ [-Wunused-variable]
   uint32_t cid;
            ^~~
../addon/rtm_controller.cc: In static member function ‘static void agora::lb_linux_sdk::RtmServerController::queryPeersOnlineStatus(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../addon/rtm_controller.cc:341:7: warning: unused variable ‘result’ [-Wunused-variable]
   int result = instance->controller_->queryPeersOnlineStatus(peerIds, length, requestId);
       ^~~~~~
../addon/rtm_controller.cc: In static member function ‘static void agora::lb_linux_sdk::RtmServerController::onEvent(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../addon/rtm_controller.cc:353:17: warning: unused variable ‘status’ [-Wunused-variable]
     napi_status status = napi_get_value_nodestring_(args[0], eventName);
                 ^~~~~~
../addon/rtm_controller.cc: In member function ‘virtual void agora::lb_linux_sdk::RtmServerController::onQueryPeersOnlineStatusResult(long long int, const agora::rtm::PeerOnlineStatus*, int, agora::rtm::QUERY_PEERS_ONLINE_STATUS_ERR)’:
../addon/rtm_controller.cc:470:16: error: ‘struct agora::lb_linux_sdk::RtmServerController::PeerOnlineStatus’ has no member named ‘onlineState’; did you mean ‘PeerOnlineStatus’?
     peerStatus.onlineState = peersStatus[i].onlineState;
                ^~~~~~~~~~~
                PeerOnlineStatus
../addon/rtm_controller.cc:470:45: error: ‘const struct agora::rtm::PeerOnlineStatus’ has no member named ‘onlineState’; did you mean ‘PeerOnlineStatus’?
     peerStatus.onlineState = peersStatus[i].onlineState;
                                             ^~~~~~~~~~~
                                             PeerOnlineStatus
../addon/rtm_controller.cc: In lambda function:
../addon/rtm_controller.cc:486:104: error: ‘const value_type {aka const struct agora::rtm::PeerOnlineStatus}’ has no member named ‘onlineState’; did you mean ‘PeerOnlineStatus’?
           peerStatus->Set(Nan::New<String>("onlineState").ToLocalChecked(), Nan::New<Uint32>(status[i].onlineState));
                                                                                                        ^~~~~~~~~~~
                                                                                                        PeerOnlineStatus
../addon/rtm_controller.cc: In static member function ‘static void agora::lb_linux_sdk::RtmChannel::onEvent(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../addon/rtm_controller.cc:643:17: warning: unused variable ‘status’ [-Wunused-variable]
     napi_status status = napi_get_value_nodestring_(args[0], eventName);
                 ^~~~~~
agorasdk.target.mk:110: recipe for target 'Release/obj.target/agorasdk/addon/rtm_controller.o' failed
make: *** [Release/obj.target/agorasdk/addon/rtm_controller.o] Error 1
make: Leaving directory '/home/risky-boy/Documents/Projects/Agora/Agora-RTM-Nodejs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/risky-boy/.nvm/versions/node/v8.16.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 5.0.0-32-generic
gyp ERR! command "/home/risky-boy/.nvm/versions/node/v8.16.2/bin/node" "/home/risky-boy/.nvm/versions/node/v8.16.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/risky-boy/Documents/Projects/Agora/Agora-RTM-Nodejs
gyp ERR! node -v v8.16.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! agora-node-rtm@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the agora-node-rtm@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/risky-boy/.npm/_logs/2019-11-28T19_22_17_958Z-debug.log

**Comment by plutoless** [comment]
works fine on my side. 
Please ensure you are using latest RTM sdk from agora official website, i.e. 1.2.0
